on:
  schedule:
    - cron: '33 4 * * *'

jobs:
  chrome-web-store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: last-execution
        name: Get the last execution time
        run: |
          curl -fsSL -O https://api.github.com/repos/foooomio/my-slack-app/actions/workflows/daily.yml/runs
          echo "::set-output name=time::$(jq -r '.workflow_runs[0].updated_at' runs)"
      - run: node dist/chrome-web-store/check-for-updates.js ${{ steps.last-execution.outputs.time }}
        env:
          GENERAL_SLACK_WEBHOOK_URL: ${{ secrets.GENERAL_SLACK_WEBHOOK_URL }}
          VIEW_BACKGROUND_IMAGE_SLACK_WEBHOOK_URL: ${{ secrets.VIEW_BACKGROUND_IMAGE_SLACK_WEBHOOK_URL }}
          NICOREPO_FILTER_SLACK_WEBHOOK_URL: ${{ secrets.NICOREPO_FILTER_SLACK_WEBHOOK_URL }}
          TWEET_BUTTON_WEBEXT_SLACK_WEBHOOK_URL: ${{ secrets.TWEET_BUTTON_WEBEXT_SLACK_WEBHOOK_URL }}
