on:
  schedule:
    - cron: '20 * * * *'

jobs:
  space-pikopikoplanet-check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: last-execution
        name: Get the last execution time
        run: |
          url="https://api.github.com/repos/foooomio/my-slack-app/actions/workflows/hourly.yml/runs?status=success&per_page=1"
          echo "::set-output name=time::$(curl -fsSL "$url" | jq -r '.workflow_runs[0].updated_at')"
      - run: node dist/space-pikopikoplanet/check-for-updates.js ${{ steps.last-execution.outputs.time }}
        env:
          SPACE_PIKOPIKOPLANET_FIREBASE_PROJECT_ID: ${{ secrets.SPACE_PIKOPIKOPLANET_FIREBASE_PROJECT_ID }}
          SPACE_PIKOPIKOPLANET_SLACK_WEBHOOK_URL: ${{ secrets.SPACE_PIKOPIKOPLANET_SLACK_WEBHOOK_URL }}
