on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  kohhi-net-check-users:
    if: ${{ false }} # temporarily disabled
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kohhi-net
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --production --frozen-lockfile
      - run: yarn ts-node -T check-users
        env:
          KOHHI_NET_SLACK_WEBHOOK_URL: ${{ secrets.KOHHI_NET_SLACK_WEBHOOK_URL }}
