on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  kohhi-net-check-users:
    if: ${{ false }} # temporarily disabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node dist/kohhi-net/check-users.js
        env:
          KOHHI_NET_SLACK_WEBHOOK_URL: ${{ secrets.KOHHI_NET_SLACK_WEBHOOK_URL }}
